### ISSUE TITLE
Build Error on Windows of the latest version

### ISSUE THREAD

**Issue by magic282** [dmlc/mxnet#4879]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Windows server 2012R2
Compiler:
VS 2013
Package used (Python/R/Scala/Julia):
Python 3
MXNet version:
Or if installed from source:
commit 30df58cae6cd707c76f09c5703e396dc8b8b2eb7
Build with CUDA 8.0, without CUDNN or OPENCV.
cmake config:
![image](https://cloud.githubusercontent.com/assets/2285145/22615906/586154e8-eadb-11e6-9187-8ce0055af610.png)

## Error Message:
Error	462	error C1001: An internal error has occurred in the compiler.	D:\mxnet\nnvm\src\pass\order_mutation.cc	114	1	

full log:
https://gist.github.com/magic282/bfce5361babbbac52a3783b98067d249

## Minimum reproducible example
No idea about how to reproduce it.
VS reports 464 warnings and 1 error.

## What have you tried to solve it?

1. I can successfully build early versions. To update to the latest, I found that I cannot build it.

**Comment by piiswrong** [comment]
try update vs to 2015.

**Comment by magic282** [comment]
Still failed. Using released dll now.
