### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'next'

### ISSUE THREAD

**Issue by R1ncy** [dmlc/mxnet#5612]
## Environment info
Operating System: ubuntu16.04

Package used (Python/R/Scala/Julia): python3.5

MXNet version: 0.9.5

## Error Message:
Traceback (most recent call last):
  File "/home/rincy/PycharmProjects/ClassifyEvent/mxmodel/embedding_train.py", line 88, in <module>
    train_model(args, mx.cpu(0))
  File "/home/rincy/PycharmProjects/ClassifyEvent/mxmodel/embedding_train.py", line 81, in train_model
    num_epoch=args.num_epoch)
  File "/usr/local/lib/python3.5/dist-packages/mxnet-0.9.5-py3.5.egg/mxnet/module/base_module.py", line 466, in fit
    next_data_batch = data_iter.next()
AttributeError: 'generator' object has no attribute 'next'

## Minimum reproducible example
Here is the code of data iterator. 
https://github.com/R1ncy/issue/blob/master/dataiterator.py
When I run this code under the environment of mxnet-0.9.4, everything went fine and I can get the evaluate score, model checkpoint.
But when I update mxnet to 0.9.5, it returns this error.

## What have you tried to solve it?

I find these pages which related to this issue.
http://stackoverflow.com/questions/21622193/python-3-2-coroutine-attributeerror-generator-object-has-no-attribute-next
http://www.1000seo.com/soft/1770
I know little about py2. Is the difference between py3 and py2 causes this issue?
How to solve it? Thanks for your attention.

**Comment by piiswrong** [comment]
Please pull master and see if its fixed
