### ISSUE TITLE
failed to compile on Mac OS X 10.11.3

### ISSUE THREAD

**Issue by ascust** [dmlc/mxnet#1378]
hi guys, 
I failed to compile on my Macbook with Mac OS X 10.11.3. The output is:
....
mxnet::io::ImageRecordIOParser::ParseNext(std::__1::vector<mxnet::io::InstVector, std::__1::allocator<mxnet::io::InstVector> >*) in iter_image_recordio.o
  "cv::imdecode(cv::_InputArray const&, int)", referenced from:
      _main in im2rec-352b28.o
      mxnet::io::ImageRecordIOParser::ParseNext(std::__1::vector<mxnet::io::InstVector, std::__1::allocator<mxnet::io::InstVector> >*) in iter_image_recordio.o
  "cv::imencode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cv::_InputArray const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&, std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
      _main in im2rec-352b28.o
  "cv::Mat::copyTo(cv::_OutputArray const&) const", referenced from:
      _main in im2rec-352b28.o
  "vtable for cv::_InputArray", referenced from:
      _main in im2rec-352b28.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/im2rec] Error 1

I have referred to many similar issues before and followed the same instruction. However, the failure continues. I installed opencv from brew and tried both embedded BLAS and openblas. I also changed the gcc and g++ to clang and clang++. Now I am only trying to build CPU only version but without any success. Any advice guys? I would really appreciate it.

**Comment by piiswrong** [comment]
You didn't post the original error

**Comment by ascust** [comment]
I finally found the problem. The thing was I didn't install pkg-config, which is a dependency for building OpenCV. I think you should add this to the tutorial that "be sure to install all the dependencies for Opencv when using homebrew" since it does not do it automatically. Thanks, I am gonna close this.
