### PR TITLE
fix cmake build with vs2015+cuda8.0+win7

### PR DESCRIPTION
**Pull request by tornadomeet**
related to https://github.com/dmlc/mxnet/issues/2924 
win7 + vs2015 + cuda8.0 + cuDNN5.1(cpu build is ok), log is: 

the error happens in  
``` C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(229): error : identifier "IUnknown" is undefined [C:\gadgetron\projects\compiling\gadgetron\toolboxes\nfft\gpu\gadgetron_toolbox_gpunfft.vcxproj]```

after add one line ```add_definitions(-DWIN32_LEAN_AND_MEAN)``` in CMakeList.txt, it will build ok.
@yajiedesign @piiswrong

### CODE REVIEW

**Comment by yajiedesign** [comment]
lgtm
